In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
url = 'https://raw.githubusercontent.com/mwitiderrick/stockprice/master/NSE-TATAGLOBAL.csv'
dataset_train = pd.read_csv(url)
training_set = dataset_train.iloc[:, 1:2].values

In [3]:
dataset_train

Date    Open    High     Low    Last   Close  \
0     2018-09-28  234.05  235.95  230.20  233.50  233.75   
1     2018-09-27  234.55  236.80  231.10  233.80  233.25   
2     2018-09-26  240.00  240.00  232.50  235.00  234.25   
3     2018-09-25  233.30  236.75  232.00  236.25  236.10   
4     2018-09-24  233.55  239.20  230.75  234.00  233.30   
...          ...     ...     ...     ...     ...     ...   
2030  2010-07-27  117.60  119.50  112.00  118.80  118.65   
2031  2010-07-26  120.10  121.00  117.10  117.10  117.60   
2032  2010-07-23  121.80  121.95  120.25  120.35  120.65   
2033  2010-07-22  120.30  122.00  120.25  120.75  120.90   
2034  2010-07-21  122.10  123.00  121.05  121.10  121.55   

      Total Trade Quantity  Turnover (Lacs)  
0                  3069914          7162.35  
1                  5082859         11859.95  
2                  2240909          5248.60  
3                  2349368          5503.90  
4                  3423509          7999.55  
...                    ...              ...  
2030                586100           694.98  
2031                658440           780.01  
2032                281312           340.31  
2033                293312           355.17  
2034                658666           803.56  

[2035 rows x 8 columns]

In [4]:
dataset_train.shape

(2035, 8)

In [5]:
dataset_train.size

16280

In [7]:
training_set.shape

(2035, 1)

In [10]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range=(0,1))
training_set_scaled = sc.fit_transform(training_set)

In [22]:
training_set_scaled.shape

(2035, 1)

In [30]:
training_set_scaled[2]

array([0.64436334])

In [64]:
X_train = []
y_train = []

for i in range(60, 2035):
    X_train.append(training_set_scaled[i-60:i, 0])
    y_train.append(training_set_scaled[i, 0])
X_train, y_train = np.array(X_train), np.array(y_train)
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))

In [65]:
X_train.shape

(1975, 60, 1)

In [66]:
X_train

array([[[0.6202352 ],
        [0.62226277],
        [0.64436334],
        ...,
        [0.79622871],
        [0.81062449],
        [0.74371452]],

       [[0.62226277],
        [0.64436334],
        [0.61719384],
        ...,
        [0.81062449],
        [0.74371452],
        [0.77007299]],

       [[0.64436334],
        [0.61719384],
        [0.61820762],
        ...,
        [0.74371452],
        [0.77007299],
        [0.73641525]],

       ...,

       [[0.19870235],
        [0.21796431],
        [0.21553122],
        ...,
        [0.14963504],
        [0.14801298],
        [0.15815085]],

       [[0.21796431],
        [0.21553122],
        [0.20600162],
        ...,
        [0.14801298],
        [0.15815085],
        [0.16504461]],

       [[0.21553122],
        [0.20600162],
        [0.21654501],
        ...,
        [0.15815085],
        [0.16504461],
        [0.15896188]]])

In [63]:
X_train

array([[0.6202352 , 0.62226277, 0.64436334, ..., 0.79622871, 0.81062449,
        0.74371452],
       [0.62226277, 0.64436334, 0.61719384, ..., 0.81062449, 0.74371452,
        0.77007299],
       [0.64436334, 0.61719384, 0.61820762, ..., 0.74371452, 0.77007299,
        0.73641525],
       ...,
       [0.19870235, 0.21796431, 0.21553122, ..., 0.14963504, 0.14801298,
        0.15815085],
       [0.21796431, 0.21553122, 0.20600162, ..., 0.14801298, 0.15815085,
        0.16504461],
       [0.21553122, 0.20600162, 0.21654501, ..., 0.15815085, 0.16504461,
        0.15896188]])

In [61]:
1975, 60

(1975, 60)

In [59]:
y_train

array([0.77007299, 0.73641525, 0.73763179, ..., 0.16504461, 0.15896188,
       0.16626115])

In [50]:
training_set_scaled[2:62, 0]

array([0.64436334, 0.61719384, 0.61820762, 0.62408759, 0.62793998,
       0.63584753, 0.61658556, 0.57725061, 0.54845904, 0.57339822,
       0.57339822, 0.56731549, 0.57948094, 0.57137064, 0.63706407,
       0.62814274, 0.63219789, 0.62550689, 0.61942417, 0.63219789,
       0.61111111, 0.62206002, 0.64557989, 0.67234388, 0.66058394,
       0.64760746, 0.6283455 , 0.62408759, 0.61597729, 0.63341444,
       0.63077859, 0.63321168, 0.64841849, 0.62469586, 0.62814274,
       0.61394972, 0.67964315, 0.65815085, 0.6593674 , 0.64841849,
       0.62773723, 0.67883212, 0.66058394, 0.63990268, 0.60888078,
       0.6431468 , 0.6784266 , 0.65064882, 0.71695053, 0.74574209,
       0.7676399 , 0.78548256, 0.78994323, 0.75892133, 0.76520681,
       0.79622871, 0.81062449, 0.74371452, 0.77007299, 0.73641525])

In [56]:
training_set_scaled[1,0]

0.6222627737226277

In [23]:
X_train.shape

(1975, 60, 1)

In [25]:
1975 * 60

118500

In [34]:
2000/60

33.333333333333336